// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3XmtY1dBv-EgnGOWtj9q7bw-O6iqOgqY',
    appId: '1:205405743523:web:9e2c2c9e6bf5fa6e4f5216',
    messagingSenderId: '205405743523',
    projectId: 'spotify-clone-5d3d6',
    authDomain: 'spotify-clone-5d3d6.firebaseapp.com',
    storageBucket: 'spotify-clone-5d3d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu1WDUgLBZIkix5UXfnGtDpGnyRJsEN9k',
    appId: '1:205405743523:android:254480829dbe6e714f5216',
    messagingSenderId: '205405743523',
    projectId: 'spotify-clone-5d3d6',
    storageBucket: 'spotify-clone-5d3d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25w9_eom2IM0yi-PNaFGtMgtSeMYNrVE',
    appId: '1:205405743523:ios:3912fc9c9b68e2ef4f5216',
    messagingSenderId: '205405743523',
    projectId: 'spotify-clone-5d3d6',
    storageBucket: 'spotify-clone-5d3d6.firebasestorage.app',
    iosBundleId: 'com.example.myMusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25w9_eom2IM0yi-PNaFGtMgtSeMYNrVE',
    appId: '1:205405743523:ios:3912fc9c9b68e2ef4f5216',
    messagingSenderId: '205405743523',
    projectId: 'spotify-clone-5d3d6',
    storageBucket: 'spotify-clone-5d3d6.firebasestorage.app',
    iosBundleId: 'com.example.myMusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3XmtY1dBv-EgnGOWtj9q7bw-O6iqOgqY',
    appId: '1:205405743523:web:3c94cf03ec4ab3714f5216',
    messagingSenderId: '205405743523',
    projectId: 'spotify-clone-5d3d6',
    authDomain: 'spotify-clone-5d3d6.firebaseapp.com',
    storageBucket: 'spotify-clone-5d3d6.firebasestorage.app',
  );
}
